using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace ImageLibrary.MongoDB.ApplicationBase.Entity
{
    public interface IEntity<TPrimaryKey>
    {
        //     Unique identifier for this entity.
        //     standard BSonId generated by MongoDb
        [BsonId]
        TPrimaryKey Id { get; set; }
    }
}
